### ISSUE TITLE
Arduino Tutorial #1 - (Michele)

### ISSUE THREAD

**Issue by FFAxKenny** [scel-hawaii/tutorials#1]
Re-create the EE 260 Racquetball lab. Nice and easy with an Arduino. More information to follow. Original lab can be found here: http://www-ee.eng.hawaii.edu/~tep/EE260/Labsnew/Lab8/lab8.html

## Task 1 First Tutorial:
http://arduino.cc/en/Tutorial/Blink

Note: the first tutorial is do-able without an LED. There is an LED already attached to pin 13, so you should be able to blink it.

## Task 2 - External LED

Hook up an external LED to a different pin, and make it blink.

## Task 3 - Knight Rider

Re-create racquetball with multiple LEDs; just have the LEDs bounce back and forth:
![giphy](https://cloud.githubusercontent.com/assets/1109418/6198528/7a23674c-b3ab-11e4-8b4c-ca24949a96f3.gif)

### Sub-Task 1 - Buttons, Buttons, Buttons

Buttons are very useful physical devices that can be used for input. Here is how buttons are hooked up using a pull-up resistor:

![511568b6ce395f1b40000000](https://cloud.githubusercontent.com/assets/1109418/6198493/0544eefc-b3a9-11e4-9912-dba39ebde64c.jpg)

This page can provide more insight on pull-up resistors and why they are used for buttons: https://learn.sparkfun.com/tutorials/pull-up-resistors

### Sub-Task 2

The button you have should be a momentary push-button; add some input to task 3 and make it a complete racquetball.

**Comment by mkshimod** [comment]
@FFAxKenny May I have more information?

**Comment by FFAxKenny** [comment]
You should have an update by the end of the day.

On Tue, Feb 10, 2015 at 10:48 AM, mkshimod <notifications@github.com> wrote:

> @FFAxKenny <https://github.com/FFAxKenny> May I have more information?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scel-hawaii/tutorials/issues/1#issuecomment-73780595>.
>



-- 

luong97@hawaii.edu
*Computer Engineering  |  *University of Hawaii at Manoa  |  Class of 2015
*Chair  *|  IEEE Student Branch  |  University of Hawaii at Manoa | 2014
*Vice President of IT  *|  Engineer's Council at the University of Hawaii |
2013

**Comment by FFAxKenny** [comment]
@mkshimod: updated the description with initial tutorial

**Comment by FFAxKenny** [comment]
Push up code when you can!
