### ISSUE TITLE
Find some projects or topics that sound intriguing.

### ISSUE THREAD

**Issue by FFAxKenny** [scel-hawaii/tutorials#2]
Find some interesting projects on the internet, and report back. Here are some good places to start:

* http://hackaday.com/
* http://hackaday.com/category/arduino-hacks/ (specifically for arduino stuff)
* https://learn.sparkfun.com/start_a_project
* https://learn.sparkfun.com/tutorials

Since our lab is the "smart campus energy lab", try and find or create something that is related to sustainability.

**Comment by mkshimod** [comment]
@FFAxKenny https://docs.google.com/a/hawaii.edu/document/d/1y1UQrTD-FxNuHrJoAqfMc79TSpFTcR8wjO4D5CmgvTI/edit?usp=sharing

**Comment by FFAxKenny** [comment]
@mkshimod: should be committed into the repository

**Comment by FFAxKenny** [comment]
bump
